version: 2
updates:
  # Node.js dependencies (e.g., package.json, package-lock.json, yarn.lock)
  - package-ecosystem: "npm" # Package manager for JavaScript projects
    directory: "/"           # Root directory where package.json is located
    schedule:
      interval: "weekly"     # Update dependencies weekly
      time: "00:00"          # Time of the update (UTC)
    open-pull-requests-limit: 10 # Limit the number of open PRs for updates

  # GitHub Actions dependencies (e.g., action versions in workflows)
  - package-ecosystem: "github-actions" # Update GitHub Actions workflows
    directory: "/"                      # Root directory of the repository
    schedule:
      interval: "weekly"
      time: "00:00"
    open-pull-requests-limit: 5
